/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "substring.h"

bool_t
xdr_string_pair (XDR *xdrs, string_pair *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->s1, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->s2, ~0))
		 return FALSE;
	return TRUE;
}
