/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUBSTRING_H_RPCGEN
#define _SUBSTRING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct string_pair {
	char *s1;
	char *s2;
};
typedef struct string_pair string_pair;

#define SUBSTRING_PROG 0xD2B44F1
#define SUBSTRING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IS_SUBSTRING 1
extern  bool_t * is_substring_1(string_pair *, CLIENT *);
extern  bool_t * is_substring_1_svc(string_pair *, struct svc_req *);
extern int substring_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IS_SUBSTRING 1
extern  bool_t * is_substring_1();
extern  bool_t * is_substring_1_svc();
extern int substring_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_string_pair (XDR *, string_pair*);

#else /* K&R C */
extern bool_t xdr_string_pair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUBSTRING_H_RPCGEN */
